deployment: 
  image: registry.gitlab.com/developerdurp/durpapi
  tag: ""
  imagePullPolicy: Always
  secretfile: durpapi-secret
  hpa:
    minReplicas: 3
    maxReplicas: 10
  probe:
    readiness:  
      httpGet:
        path: /api/health/getHealth
        port: 8080
    liveness: 
      httpGet:
        path: /api/health/getHealth
        port: 8080
    startup: 
      httpGet:
        path: /api/health/getHealth
        port: 8080

service:
  type: ClusterIP
  port: 80
  targetport: 8080

swagger:
  host: api.durp.info

postgresql:
  enabled: false
